# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.3.1'
    hooks:
      - id: poetry-export
        name: poetry-export
        args: ["--without-hashes", "-o", "requirements.txt" ]
      - id: poetry-export
        name: poetry-export-dev
        args: ["--without-hashes", "--with", "dev", "-o", "requirements-dev.txt" ]
      - id: poetry-export
        name: poetry-export-test
        args: ["--without-hashes", "--with", "test", "-o", "requirements-test.txt" ]
      - id: poetry-export
        name: poetry-export-license
        args: ["--without-hashes", "--with", "license", "-o", "requirements-license.txt" ]
  - repo: local
    hooks:
      - id: pysen-lint
        name: pysen-lint
        entry: pysen run lint
        language: python
        types: [file, python]
        stages: [push]
        pass_filenames: false
      - id: poetry-export-check
        name: poetry-export-check
        entry: python poetry_export_check.py
        language: python
        stages: [commit]
