# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: pysen-lint
        name: pysen-lint
        entry: pysen run lint
        language: python
        types: [file, python]
        stages: [push]
        pass_filenames: false
      - id: poetry-export
        name: poetry-export
        entry: python poetry_export_all.py
        language: python
        stages: [commit]
