# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: pysen-lint
        name: pysen-lint
        entry: pysen run lint
        language: python
        types: [file, python]
        stages: [push]
        pass_filenames: false
      - id: poetry-export
        name: poetry-export
        entry: poetry export --without-hashes -o requirements.txt
        language: python
        stages: [commit]
        pass_filenames: false
      - id: poetry-export-dev
        name: poetry-export-dev
        entry: poetry export --without-hashes --with dev -o requirements-dev.txt
        language: python
        stages: [commit]
        pass_filenames: false
      - id: poetry-export-test
        name: poetry-export-test
        entry: poetry export --without-hashes --with test -o requirements-test.txt
        language: python
        stages: [commit]
        pass_filenames: false
      - id: poetry-export-license
        name: poetry-export-license
        entry: poetry export --without-hashes --with license -o requirements-license.txt
        language: python
        stages: [commit]
        pass_filenames: false

#  - repo: https://github.com/python-poetry/poetry
#    rev: '1.3.1'
#    hooks:
#      - id: poetry-check
#      - id: poetry-lock
#      - id: poetry-export
#        args: ["--without-hashes", "-o", "requirements.txt" ]
