name: test

env:
  POETRY_VERSION: '1.3.1'

on:
  push:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest] # [ubuntu-20.04, macos-latest, windows-latest]
        python: ["3.11.3"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: poetry

      - name: Install poetry
        run: pip3 install poetry

      - name: Install libraries for ubuntu
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt-get install libsndfile1

      - name: Check poetry
        uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
        run: |
          poetry export --without-hashes -o requirements.txt
          poetry export --without-hashes --with dev -o requirements-dev.txt
          poetry export --without-hashes --with test -o requirements-test.txt
          poetry export --without-hashes --with license -o requirements-license.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements-test.txt

      - run: pysen run lint

      - name: Run pytest and get coverage
        run: |
          coverage run --omit=test/* -m pytest

      - name: Submit coverage to Coveralls
        if: matrix.os == 'ubuntu-20.04'
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create coverage result
        if: github.event_name == 'pull_request' && matrix.os == 'ubuntu-20.04'
        run: |
          mkdir report
          coverage report > report/report.txt
          echo ${{ github.event.number }} > report/pr_num.txt

      - name: Upload coverage result
        if: github.event_name == 'pull_request' && matrix.os == 'ubuntu-20.04'
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report/

      - name: Check licenses
        shell: bash
        run: |
          OUTPUT_LICENSE_JSON_PATH=/dev/null \
          bash build_util/create_venv_and_generate_licenses.bash
